### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by davisford** [scttnlsn/mubsub#35]
```sh
TypeError: Cannot read property '0' of undefined
    at /node_modules/mubsub/lib/channel.js:198:39
    at /node_modules/mubsub/node_modules/mongodb/lib/mongodb/collection/core.js:210:9
    at __executeInsertCommand (/node_modules/mubsub/node_modules/mongodb/lib/mongodb/db.js:1829:12)
    at Db._executeInsertCommand (/node_modules/mubsub/node_modules/mongodb/lib/mongodb/db.js:1930:5)
    at insertAll (/node_modules/mubsub/node_modules/mongodb/lib/mongodb/collection/core.js:205:13)
    at Collection.insert (/node_modules/mubsub/node_modules/mongodb/lib/mongodb/collection/core.js:35:3)
    at /node_modules/mubsub/lib/channel.js:197:28
    at /node_modules/mubsub/node_modules/mongodb/lib/mongodb/cursor.js:738:35
    at Cursor.close (/node_modules/mubsub/node_modules/mongodb/lib/mongodb/cursor.js:959:5)
    at Cursor.nextObject (/node_modules/mubsub/node_modules/mongodb/lib/mongodb/cursor.js:738:17) 
```

```sh
$npm ls --depth=0 | grep mubsub
npm info it worked if it ends with ok
npm info using npm@2.7.5
npm info using node@v0.12.2
├── mubsub@1.0.4
```

Code that generates this:

```javascript
// mubsubExample.js
'use strict';

var mubsub = require('mubsub'),
  channelNames = ['printjobs'],
  channels = {},
  client;

var l = require('../log')('config:mubsub'), log = l.log, error = l.error;

function init() {
  client = mubsub('mongodb://localhost:27017/mubsub_example');
  client.on('error', function (err) {
    error('mubsub client error ', err);
  });

  channelNames.forEach(function (n) {
    channels[n] = client.channel(n);
    channels[n].on('error', function (err) {
      error('mubsub channel[%s] error ', n, err);
    });
  });
}

function close() {
  client.close();
}

module.exports = {
  init: init,
  close: close,
  mubsub: mubsub
};
```

Then just `require('mubsubExample').init()`

Any thoughts?

**Comment by davisford** [comment]
This is using a very old Mongo driver:

```
├─┬ mubsub@1.0.4
│ └─┬ mongodb@1.3.23
│   ├── bson@0.2.5
│   └── kerberos@0.0.3
```

```
$mongod --version
db version v3.0.0
git version: nogitversion
```

Any chance you can push a new package with the latest driver?  That seems to be the issue as now I am seeing this:

```
MongoError: driver is incompatible with this server version
```

**Comment by adambarthelson** [comment]
+1

**Comment by adambarthelson** [comment]
Had to install an older version of Mongo... not ideal.  Will probably end up moving over to Redis based solutions.

**Comment by kof** [comment]
can you send a PR?

**Comment by adambarthelson** [comment]
I had to install an older version of MongoDB on the machine that mubsub is connecting to as a client.  Not something fixable on mubsub's side.  I did dig into the error above, related to the latest Mongo, and may be able to fix it given the time here soon.  Will submit a PR ASAP.

**Comment by adambarthelson** [comment]
Looks like someone may have beaten me to it: https://github.com/scttnlsn/mubsub/pull/33

Will review their PR and see if I can resolve it's conflicts.

**Comment by scttnlsn** [comment]
Mongo driver updated in https://github.com/scttnlsn/mubsub/pull/39.  Please re-open if this is still an issue.

**Comment by aschmid** [comment]
same here.
