### ISSUE TITLE
error with mongo-native 3.0+

### ISSUE THREAD

**Issue by barisusakli** [scttnlsn/mubsub#61]
```
2018-05-15T15:00:02.328Z [1628] - error:  TypeError: collection.find(...).sort(...).limit(...).nextObject is not a function
    at Channel.onCollection (c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\mubsub\lib\channel.js:204:14)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at c:\Users\Baris\Desktop\github\nodebb_vscode\NodeBB\node_modules\mubsub\lib\channel.js:119:22
```

**Comment by barisusakli** [comment]
https://github.com/mongodb/node-mongodb-native/blob/master/CHANGES_3.0.0.md#api-changes

`nextObject` was removed in 3.0.0
